In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5,6])
y = np.array([1,2,3])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [3]:
np.hstack([x,y])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [4]:
z = np.array([7,8,9,10,11,12])
xz = np.vstack([x,z])
xz

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [5]:
np.vsplit(xz, [3])

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]), array([], shape=(0, 6), dtype=int32)]

In [6]:
import pandas as pd

In [7]:
pdseries = pd.Series([1,2,3,4,5.0])
print(pdseries)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64


In [8]:
print(pdseries.values)

[ 1.  2.  3.  4.  5.]


In [9]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995}

In [10]:
print(area_dict)
type(area_dict)

{'California': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995}


dict

In [11]:
area_pd = pd.Series(area_dict)
area_pd

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
dtype: int64

In [12]:
range(4)

range(0, 4)

In [13]:
print(range(4))

range(0, 4)


In [16]:
test = np.array(range(4))
test

array([0, 1, 2, 3])

In [17]:
test2 = np.array(range(1,100, 5))
test2

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])