In [1]:
import numpy as np
import pandas as pd

In [2]:
x = np.array([1,2,3,4,5,6])
y = np.array([1,2,3])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [3]:
np.hstack([x,y])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [4]:
z = np.array([7,8,9,10,11,12])
xz = np.vstack([x,z])
xz

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [5]:
np.vsplit(xz, [3])

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]), array([], shape=(0, 6), dtype=int32)]

In [6]:
import pandas as pd

In [7]:
pdseries = pd.Series([1,2,3,4,5.0])
print(pdseries)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64


In [8]:
print(pdseries.values)

[ 1.  2.  3.  4.  5.]


In [9]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995}

In [10]:
print(area_dict)
type(area_dict)

{'California': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995}


dict

In [11]:
area_pd = pd.Series(area_dict)
area_pd

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
dtype: int64

In [12]:
range(4)

range(0, 4)

In [13]:
print(range(4))

range(0, 4)


In [14]:
test = np.array(range(4))
test

array([0, 1, 2, 3])

In [15]:
test2 = np.array(range(1,100, 5))
test2

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [16]:
pop_index = [('California', 2000), 
             ('California', 2010),
             ('New York', 2000), 
             ('New York', 2010),
             ('Texas', 2000), 
             ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]
pop = pd.Series(populations, index=pop_index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [21]:
test = pd.Series([1,2,3,4,5,6], index = ['a', 'b', 'c', 'd', 'e', 'f'])
test

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [25]:
[i for i in pop.index if i[0] == 2010]

[]

In [32]:
pop.index[4]

('Texas', 2000)

In [37]:
pop_reindex = pop.reindex(pop_index)
pop_reindex

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [42]:
pop_index_2 = pd.MultiIndex.from_arrays([['California', 2000],
                                        ['California', 2010],
                                        ['New York', 2000],
                                        ['New York', 2010],
                                        ['Texas', 2000],
                                        ['Texas', 2010]])
pop_index_2

MultiIndex(levels=[[2000, 'California'], [2010, 'California'], [2000, 'New York'], [2010, 'New York'], [2000, 'Texas'], [2010, 'Texas']],
           labels=[[1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0]])

In [44]:
pop_reindex_2 = pop_index_2.reindex(pop_index_2)
pop_reindex_2

(MultiIndex(levels=[[2000, 'California'], [2010, 'California'], [2000, 'New York'], [2010, 'New York'], [2000, 'Texas'], [2010, 'Texas']],
            labels=[[1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0]]), None)

In [48]:
pop_df = pd.DataFrame({'total': pop_reindex_2,
                     'under18': [100000,
                                200000,
                                300000,
                                400000,
                                500000,
                                600000]})

ValueError: arrays must all be same length

In [49]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [50]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [51]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [52]:
pop[:, 2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [53]:
pop_df = pd.DataFrame({'total': pop,
                       'under18': [9267089, 9284094,
                                   4687374, 4318033,
                                   5906301, 6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [56]:
percent_u18 = pop_df['under18']/pop_df['total']
percent_u18

California  2000    0.273594
            2010    0.249211
New York    2000    0.247010
            2010    0.222831
Texas       2000    0.283251
            2010    0.273568
dtype: float64

In [58]:
percent_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568